name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version-file: go.mod
    
    - name: Build binaries
      run: |
        GOOS=linux GOARCH=amd64 go build -ldflags "-s -w" -o gpx-cleaner-linux-amd64 .
        GOOS=darwin GOARCH=amd64 go build -ldflags "-s -w" -o gpx-cleaner-darwin-amd64 .
        GOOS=darwin GOARCH=arm64 go build -ldflags "-s -w" -o gpx-cleaner-darwin-arm64 .
        GOOS=windows GOARCH=amd64 go build -ldflags "-s -w" -o gpx-cleaner-windows-amd64.exe .
    
    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        files: |
          gpx-cleaner-linux-amd64
          gpx-cleaner-darwin-amd64
          gpx-cleaner-darwin-arm64
          gpx-cleaner-windows-amd64.exe